### PR TITLE
Variable base scalar multiplication

### LINKED ISSUE #276: Scalar multiplication - Verification fails for different point
The following pseudo code will fail:
```
A := a · G
B := b · G

prover_circuit {
  scalar_mul(a, B)
}

verifier_circuit {
  scalar_mul(0, A)
}
```
And the following will work
```
A := a · G
B := b · G

prover_circuit {
  scalar_mul(a, B)
}

verifier_circuit {
  scalar_mul(0, B)
}
```

We need to find a way to workaround this issue in order to perform diffie-hellman key exchange.

Here follows an example in Rust on how to reproduce the error:
```rust
use dusk_plonk::constraint_system::ecc;
use dusk_plonk::jubjub::{ExtendedPoint, GENERATOR};
use dusk_plonk::prelude::*;

use std::ops::Mul;

fn main() {
    let mut rng = rand::thread_rng();

    let bob_secret = JubJubScalar::random(&mut rng);
    let bob_public = GENERATOR.to_niels().mul(&bob_secret);

    let alice_secret = JubJubScalar::random(&mut rng);
    let alice_public = GENERATOR.to_niels().mul(&alice_secret);

    let pp = PublicParameters::setup(1 << 9, &mut rng).unwrap();
    let (ck, vk) = pp.trim(1 << 9).unwrap();

    let label = b"some-label";

    let circuit = |composer: &mut StandardComposer, secret: JubJubScalar, public: ExtendedPoint| {
        let secret = composer.add_input((secret).into());
        ecc::scalar_mul(composer, secret, public);

        composer.add_dummy_constraints();
    };

    let mut prover = Prover::new(label);
    circuit(prover.mut_cs(), alice_secret, bob_public);
    prover
        .preprocess(&ck)
        .expect("Error on preprocessing stage");
    let proof = prover.prove(&ck).expect("Error in proof generation stage");

    let mut verifier = Verifier::new(label);

    // The reason for the failure is here
    // It will not happen if we pass `bob_public` to `circuit`
    // 
    // When the provers circuit was constructed with `bob_public`, it will not accept any other
    // point different than the initially provided
    circuit(verifier.mut_cs(), JubJubScalar::zero(), alice_public);

    verifier
        .preprocess(&ck)
        .expect("Error on preprocessing stage");

    assert!(verifier
        .verify(&proof, &vk, &vec![BlsScalar::zero()])
        .is_ok())
}
```

### LINKED ISSUE #279: Variable Base Scalar multiplication custom gate implementation
With the actual `ecc` module we have implemented for our `StandardComposer` it is not possible to perform var_base scalar mul circuits with a good performance.

Create a gadget for it which does a "work-arround" to that but as it was computed by @kevaundray , the number of constraints will be ~9000.

Therefore, since we will need that for zedger and other circuits, we should take the decision of whether is worth it or not to go for an implementation of a custom gate which provides that functionality.

The average amount of gates that it will take to do var_base scalar mul (as @kevaundray  said) was about 500 as much.

In respect to the API changes/break, the only gate that will get it's API changed is the `poly_gate` which will need to include an extra selector_poly coefficient. But the rest of the gates should still have the same API even if the underlying code changes, so I'm not worried about huge migrations TBH, it should be pretty simple to move from`v0.2.6` to the new version.

So since this is the RFC , I'll like to hear from @ZER0 @toghrulmaharramov @kevaundray @autholykos .

Also, I think it would be helpful if @kevaundray could provide some sort of "time estimation" for this impl. 

See #276 to get some background

### LINKED ISSUE #281: ECC Scalar multiplication - Private generator
Currently the `dusk_plonk::constraint_system::ecc::scalar_mul` accepts the secret as `Variable` and `generator` as open.

We need to have the ability to input the generator secretly.

One use case for that is the ElGamal encryption. The cipher is defined as follows:
* M - Message
* P - Public
* G - Generator
* s - Secret
```rust
let K = s · G;
let C = M + s · P;
```

The broadcasted information is the tuple `(K, C)`. The protocol itself doesn't force the broadcast of `P`, but this would be required if we want to prove the knowledge of an encrypted message if `scalar_mul` demands an open generator. Ideally, the circuit would be as follows:

`elgamal_message_knowledge(s: &Variable, P: &Point, G: &ExtendedPoint, M: &Point)`

We would then proceed with the following pseudo-code
```
K = scalar_mul(s, G)
C = scalar_mul_witness(s, P)
C = curve_addition(C, M)
return (K, C)
```

### PR DESCRIPTION
**Pull request by kevaundray**
This PR introduces a new custom gate for curve addition, so that the addition of two variable base points will cost 2 gates.

It also adds a function to compute scalar multiplication with a variable base point. This is different to the more efficient fixed base scalar multiplication which encodes the fixed point into the circuit.

The previous number of constraints for variable base scalar multiplication was ~10K. This PR reduces this number to ~2K.

The break down is as follows:

- **Scalar decomposition** : _504_ constraints. 

This is not optimised fully. We have the mandatory booleanity constraints which account for 252 constraints. Then we have the accumulation phase, which for now uses one gate to accumulate. I believe we can reduce this by a third by accumulating more three values in one gate. This would only reduce it by 84 constraints. Additionally, by adding a `c_next` we can store the current bit in that wire and add the booleanity check into the polynomial identity. This would reduce the number of constraints by 252, since you can now remove the booleanity gate. The cost of the last optimisation is an extra 32 bytes in a PLONK proof.

 A different optimisation which was initially proposed is to use base4 decomposition, which is already implemented. This would make scalar decomposition 63 constraints. However, I neglected to include the numbers for the modified "quadruple-and-add" or whichever new algorithm would be needed to account for the change in base.

- **Double and Add** : _6_ constraints per bit

- We use the same algorithm for doubling and adding. This gives us a cost of 4 gates.

- Conditionally selecting the identity point, carries a cost of two gates.

closes #281 , closes #279 , closes #276

### CODE REVIEW

File: src/constraint_system/ecc/curve_addition/gate.rs [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+        composer
+            .perm
+            .add_variables_to_map(x_3, y_3, composer.zero_var, x_1_y_2, composer.n);
+        composer.n += 1;
+
+        Point { x: x_3, y: y_3 }
+    }
+}
+
+// XXX: JubJub does not allow us to create a point from X and Y
```
Comment (CPerezz) [inline src/constraint_system/ecc/curve_addition/gate.rs:91]: It does.

See in lib.rs : 
```rust
/// Constructs an AffinePoint given `x` and `y` without checking
    /// that the point is on the curve.
    pub const fn from_raw_unchecked(x: Fq, y: Fq) -> AffinePoint {
        AffinePoint { x, y }
    }
```
