### PR TITLE
Fix "alloc" feature for tests

### LINKED ISSUE #346: Add back examples folder for the crate
After we started to release new versions of this crate. The `examples` folder was removed since we weren't able to keep it up to date due to the refactors we were performing.

I think it's a good source of knowledge for the newcomers to the repo and also allows the users to see how to interact with the library on the "recommended way".

### PR DESCRIPTION
**Pull request by moCello**
Also add an example for creating a circuit.

Resolves #346

### CODE REVIEW

File: examples/circuit.rs [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+// 4) a * b + d = 42
+// 5) JubJub::GENERATOR * e(JubJubScalar) = f where F is a Public Input
+impl Circuit for TestCircuit {
+    fn circuit(&self, composer: &mut Composer) -> Result<(), Error> {
+        let a = composer.append_witness(self.a);
+        let b = composer.append_witness(self.b);
+        let d = composer.append_witness(self.d);
+
+        // 1) a < 2^6
+        const HALF_SIX: usize = 3;
```
Comment (xevisalle) [inline examples/circuit.rs:34]: I remember that you explained me the reason for that, but I can't remember it now. As such, maybe would be a good moment to fix this? Probably more people will have the same doubt...

**Review by xevisalle — APPROVED** [review]
LGTM, just consider the comment I added.

File: README.md [hunk 2]
```diff
@@ -15,78 +15,7 @@ an exhaustive security analysis. Use at your own risk.
...
-    .expect("failed to prove");
-
-// Verify the generated proof
-verifier
-    .verify(&proof, &public_inputs)
-    .expect("failed to verify proof");
-```
+Check the 'examples' directory for the usage.
 
 ### Features
```
Comment (xevisalle) [inline README.md:20]: remove one #

File: examples/circuit.rs (hunk 1 above)
Comment (moCello) [reply examples/circuit.rs:34]: The range component can only operate with even numbers. This is why we give it half of the number we want to operate on, see [here](https://github.com/dusk-network/plonk/blob/master/src/composer.rs#L1002-L1011).

I was trying to convey this by introducing the constant and naming it `HALF_*` where `*` is the value that we are checking on. As much as I can see that this is far form ideal, I'm also not sure how to make this better.
Do you have a suggestion?

Comment (moCello) [reply examples/circuit.rs]: How about this:
```rust
        // 1) a < 2^6
        composer.component_range::<3>(a); // 3 BIT_PAIRS = 6 bits

        // 2) b < 2^4
        composer.component_range::<2>(b); // 2 BIT_PAIRS = 4 bits
```

Comment (xevisalle) [reply examples/circuit.rs]: is there a way to do a compile time check on the provided value? otherwise, we could also throw an error at runtime. e.g., if the provided number is not even, throw `NotEvenError: provided constant not even.`

Comment (xevisalle) [reply examples/circuit.rs]: btw, here:

https://github.com/dusk-network/plonk/blob/780bbf9c46a17ca0dd90543dfe2716833a4f56bb/src/composer.rs#L1015C9-L1016C18

it says that we need an even number because we iterate over 2-bit chunks. Can we simply add a 0 bit at the beginning of the bit array if the decimal number is odd?

Comment (moCello) [reply examples/circuit.rs]: Actually we introduced `BIT_PAIRS` to get rid of this `debug_assert` (see the discussion in #764 ).

In any case, any change in the range or logic components is not in the scope of this PR.

If you want we can open another issue on this to have the discussion.
