### PR TITLE
Fix logic_constraint assertion bug

### LINKED ISSUE #251: Assert panicking in logic_constrain_gate
When running the following code:
```rust
let should_be_true = composer.logic_xor_gate(left_assign, right_assign, 2);
```
This should never happen since the only thing that should cause this function to panic is a `num_bits` which is not even.

This error gets triggered:
```
thread 'score_gen::score::tests::correct_score_gen_proof' panicked at 'assertion failed: `(left == right)`
  left: `0x000000000000000000000000000000012c03b58947d957fd33e4168b680e3d3c`,
 right: `0x0000000000000000000000000000000000000000000000000000000000000000`', /home/kr0/.cargo/registry/src/github.com-1ecc6299db9ec823/dusk-plonk-0.1.0/src/constraint_system/composer.rs:1379:9
```

The problem is comming from:
https://github.com/dusk-network/plonk/blob/f2e889184961b885d9e095afe35b137165112c91/src/constraint_system/composer.rs#L1379

I'm not entirely sure that it corresponds to a real computation error of the gate. Since the other `assert` is passing. But we will need to investigate.

### PR DESCRIPTION
**Pull request by CPerezz**
As mentioned in #251 there was a problem with the `assert`
statements used in the "front-end" check of the PLONK program
memmory.

This was caused by a bit_num parameter set to less bits than the
actual number bit-size.
Therefore, the assert was checking the final value of the resulting
wire agains the original number provided on each input wire instead
of the value clamped to the correct ammount of bits.

Closes #251 

We also now use `dusk-bls12_381 v0.1.2`, the new version of bls is published in crates.io

### CODE REVIEW

File: src/constraint_system/logic.rs [hunk 1]
```diff
@@ -248,13 +248,22 @@ impl StandardComposer {
...
+        // specified on the fn call parameters.
         // This can be done with an `assert_equal` constraint gate or simply
         // by taking the values behind the n'th variables of `w_l` & `w_r` and
         // checking that they're equal to the original ones behind the variables
         // sent through the function parameters.
-        assert_eq!(self.variables[&a], self.variables[&self.w_l[self.n - 1]]);
-        assert_eq!(self.variables[&b], self.variables[&self.w_r[self.n - 1]]);
+        assert_eq!(
+            self.variables[&a]
+                & (Scalar::from(2u64).pow(&[(num_bits) as u64, 0, 0, 0]) - Scalar::one()),
```
Comment (ZER0) [inline src/constraint_system/logic.rs:259]: Since I start to see few places where we use this, what about having:

```rust
self.variables[&a] & Scalar::pow_of_2(num_bits) - Scalar::one(),
```

instead?
Not only it's more concise and readable, but the implementation can remove the unnecessary iteration and the array of four `u64` creation in the stack since we just pass a single value (`usize` I assume).

File: src/lib.rs [hunk 2]
```diff
@@ -81,3 +81,6 @@ pub mod notes {
     #[doc(include = "../docs/notes-KZG10.md")]
     pub mod kzg10_docs {}
 }
+
+/// Bls12_381 Scalar structure used by plonk.
+pub use dusk_bls12_381::Scalar;
```
Comment (ZER0) [inline src/lib.rs:86]: I thought we discussed about exporting the whole crate via PLONK, not just the `Scalar`.

Also, we should do that for `JubJub` as well, no?

File: Cargo.toml [hunk 3]
```diff
@@ -23,13 +23,12 @@ exclude = [
...
 edition = "2018"
 
-
 [dependencies]
 merlin = "2.0.0"
 rand = "0.7.2"
 rand_core = { version = "0.5", default-features = false }
 # Built by default with "std", "alloc", "pairing", "groups" and "endo" features.
-dusk-bls12_381 = "0.1.0"
+dusk-bls12_381 = {git = "https://github.com/dusk-network/bls12_381", tag = "0.1.2"}
```
[the remark this answers is not in the document]
Comment (CPerezz) [reply Cargo.toml:31]: We didn't push a new version of Bls since we were waiting for the ECC gate to then publish a new version of plonk with the new version of bls all at the same time.

Probably as you say it's better to just wait and use tags and releases until we define a good process to use crates.io versioning.

File: src/constraint_system/logic.rs (hunk 1 above)
Comment (CPerezz) [reply src/constraint_system/logic.rs:259]: Hmmm. I din't want to introduce much more new methods like this one. At the end, you can already do the same thing just with the `pow` method.

IMO it's not worth it.

File: src/lib.rs (hunk 2 above)
Comment (CPerezz) [reply src/lib.rs:86]: Yep, I'll do it for JubJub on a sepparated PR once a couple of PRs land in jubjub crate. 

I was just going to export the `Scalar` types from both crates instead of the whole crate. But maybe you have other ideas.

File: Cargo.toml (hunk 3 above)
[the remark this answers is not in the document]
Comment (ZER0) [reply Cargo.toml:31]: What I said previously was to avoid publish on crates.io in the first place, during the development process.
Once is published is better continue to use it otherwise we add another variable to the whole mess.

File: src/constraint_system/logic.rs (hunk 1 above)
Comment (ZER0) [reply src/constraint_system/logic.rs:259]: That would also applying to all the helper methods we already introduced: you could do the same thing (jubjub to bls, checking if is zero, and so on) so I don't see why not at this point. Our code already diverged substantially from the original repo (and not just because the helper method) so it's not like this change would impact that.

As explained the difference between using `pow` and a dedicated method is also not just in readability but in unnecessary operation involved: you pass an array (unnecessary) that you're going to fully iterate 4 times (unnecessary) every time you just want a scalar that is a power of two.

Other libraries have similar methods – if not the same – also because in general can be optimized differently from a `pow` (but even without specific optimization, just the same code of `pow` will be reduced).

File: src/lib.rs (hunk 2 above)
Comment (ZER0) [reply src/lib.rs:86]: As we discussed – as now I think it's clear – the idea to me was to re-export the whole crate so everything use PLONK can use automatically the whole jubjub / bls's crates that PLONK uses, reducing the confusion / errors about versioning, and be sure that if you use the one PLONK exports, you're good to go.
So not only the Scalars.

Comment (CPerezz) [reply src/lib.rs:86]: That will be done correctly in #256

File: src/constraint_system/logic.rs (hunk 1 above)
Comment (CPerezz) [reply src/constraint_system/logic.rs:259]: Let's open a low prio issue for it if you want. But i don't think it has to be solved in this PR.

Comment (CPerezz) [reply src/constraint_system/logic.rs:259]: Done, See https://github.com/dusk-network/plonk/issues/259

File: src/lib.rs (hunk 2 above)
Comment (CPerezz) [reply src/lib.rs]: It has been removed. Will be done in #256

File: Cargo.toml (hunk 3 above)
[the remark this answers is not in the document]
Comment (CPerezz) [reply Cargo.toml]: It is now referencing the crates.io version of BLS.
