### PR TITLE
Fix inconsistent gate ordering

### LINKED ISSUE #797: Inconsistent gate ordering
#### Summary
Within the proof system, variables are not always listed in the same order. One place where this could lead to a problem is in the arithmetic proving and verifying keys. The arithmetic prover key has “q_c before q_4”, unlike the arithmetic verifier key struct which stores “q_4 before q_c”, and strangely the verifier key serialization stores “q_c before q_4”.
The arithmetic verifier key does correctly swap q_c and q_4 in from_bytes, so there are no bugs present currently. However, swapping the order throughout the codebase is very unexpected and may lead to bugs in the future.

Recommendation: pick one ordering and stick to it throughout the library. In particular, please serialize things in the same order they are stored in the struct.

#### Relevant Context
Finding of the audit.

### PR DESCRIPTION
**Pull request by moCello**
Resolves #797

### CODE REVIEW

**Review by HDauven — APPROVED** [review]

File: tests/append_gate.rs [hunk 1]
```diff
@@ -94,7 +94,7 @@ fn append_gate() {
     let b = BlsScalar::one();
     let d = BlsScalar::one();
```
Comment (HDauven) [inline tests/append_gate.rs:95]: Would move this one around, in the spirit of ABOD ordering.

File: tests/append_gate.rs [hunk 2]
```diff
@@ -104,7 +104,7 @@ fn append_gate() {
     let b = BlsScalar::zero();
     let d = BlsScalar::zero();
     let o = -BlsScalar::one();
```
Comment (HDauven) [inline tests/append_gate.rs:106]: Same here

File: tests/append_gate.rs [hunk 3]
```diff
@@ -114,7 +114,7 @@ fn append_gate() {
     let b = BlsScalar::one();
     let d = BlsScalar::zero();
     let o = -BlsScalar::one();
```
Comment (HDauven) [inline tests/append_gate.rs:116]: Same here

File: tests/append_gate.rs [hunk 4]
```diff
@@ -124,7 +124,7 @@ fn append_gate() {
     let b = BlsScalar::one();
     let d = BlsScalar::zero();
     let o = -BlsScalar::from(3u64);
```
Comment (HDauven) [inline tests/append_gate.rs:126]: Same here

File: tests/append_gate.rs [hunk 5]
```diff
@@ -134,7 +134,7 @@ fn append_gate() {
     let b = BlsScalar::zero();
     let d = BlsScalar::one();
     let o = BlsScalar::zero();
```
Comment (HDauven) [inline tests/append_gate.rs:136]: Same here

File: tests/append_gate.rs [hunk 6]
```diff
@@ -156,7 +156,7 @@ fn append_gate() {
     let d = BlsScalar::random(&mut rng);
     let o = BlsScalar::random(&mut rng);
```
Comment (HDauven) [inline tests/append_gate.rs:157]: Same here

File: tests/append_gate.rs [hunk 7]
```diff
@@ -167,7 +167,7 @@ fn append_gate() {
     let d = BlsScalar::one();
     let o = BlsScalar::one();
```
Comment (HDauven) [inline tests/append_gate.rs:168]: Same here

**Review by HDauven — APPROVED** [review]
LGTM, small suggestion in the test file.
